/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications.index'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'
import { Route as ProductProductSlugRouteImport } from './routes/product.$productSlug'
import { Route as BlogPostSlugRouteImport } from './routes/blog.$postSlug'
import { Route as ApplicationsUseCaseRouteImport } from './routes/applications.$useCase'

const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductSlugRoute = ProductProductSlugRouteImport.update({
  id: '/product/$productSlug',
  path: '/product/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostSlugRoute = BlogPostSlugRouteImport.update({
  id: '/blog/$postSlug',
  path: '/blog/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsUseCaseRoute = ApplicationsUseCaseRouteImport.update({
  id: '/applications/$useCase',
  path: '/applications/$useCase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distributor': typeof DistributorRoute
  '/applications/$useCase': typeof ApplicationsUseCaseRoute
  '/blog/$postSlug': typeof BlogPostSlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distributor': typeof DistributorRoute
  '/applications/$useCase': typeof ApplicationsUseCaseRoute
  '/blog/$postSlug': typeof BlogPostSlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/applications': typeof ApplicationsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distributor': typeof DistributorRoute
  '/applications/$useCase': typeof ApplicationsUseCaseRoute
  '/blog/$postSlug': typeof BlogPostSlugRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/distributor'
    | '/applications/$useCase'
    | '/blog/$postSlug'
    | '/product/$productSlug'
    | '/products/$category'
    | '/applications/'
    | '/blog/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/distributor'
    | '/applications/$useCase'
    | '/blog/$postSlug'
    | '/product/$productSlug'
    | '/products/$category'
    | '/applications'
    | '/blog'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/distributor'
    | '/applications/$useCase'
    | '/blog/$postSlug'
    | '/product/$productSlug'
    | '/products/$category'
    | '/applications/'
    | '/blog/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DistributorRoute: typeof DistributorRoute
  ApplicationsUseCaseRoute: typeof ApplicationsUseCaseRoute
  BlogPostSlugRoute: typeof BlogPostSlugRoute
  ProductProductSlugRoute: typeof ProductProductSlugRoute
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productSlug': {
      id: '/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/product/$productSlug'
      preLoaderRoute: typeof ProductProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postSlug': {
      id: '/blog/$postSlug'
      path: '/blog/$postSlug'
      fullPath: '/blog/$postSlug'
      preLoaderRoute: typeof BlogPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$useCase': {
      id: '/applications/$useCase'
      path: '/applications/$useCase'
      fullPath: '/applications/$useCase'
      preLoaderRoute: typeof ApplicationsUseCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DistributorRoute: DistributorRoute,
  ApplicationsUseCaseRoute: ApplicationsUseCaseRoute,
  BlogPostSlugRoute: BlogPostSlugRoute,
  ProductProductSlugRoute: ProductProductSlugRoute,
  ProductsCategoryRoute: ProductsCategoryRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
